### PR TITLE
Added Compatibility for Latest HiDev Build

### PR DESCRIPTION
**Pull request by LifeCore-Development**
Tested Basic Functions on my own server with no issues. There will probably be bugs or errors. But a lot of the new HiDev Stuff isnt included in the server/main.lua of LSN-Evidence

### CODE REVIEW

**Comment by LeSiiN** [comment]
Could u remove the version check, i dont think we need that in this script, because the policejob itself does that already. Everything else seems okay

**Comment by LeSiiN** [comment]
@RazerGhost could u take a look at this, i dont have the policejob. And pls make sure the lab works.

**Comment by LifeCore-Development** [comment]
Ill run a test on the lab, and remove the version check give me a little bit.

**Comment by LifeCore-Development** [comment]
Im looking into the labs, it seems like HiDev did most the work supporting the new inventory by QB, but hasnt made the labs work with it, its missing the entire chunk. Working on a fix for it.

**Comment by LifeCore-Development** [comment]
Got the lab working with the new config option for new-qb-inventory (I didnt change any more code that isnt related)
It needs a modification to the evidence.lua. I dont really use github so idk how to put it in the same Pull Request.

**Comment by RazerGhost** [comment]
Started my test yesterday but didnt finish everything yet :)

**Comment by RazerGhost** [comment]
@LifeCore-Development if you fix https://github.com/LifeCore-Development/lsn-evidence/blob/5ecd7e98fc073b6a73016f43b54ebe1d2a605160/%5Bhi-dev%20-%20qb-policejob%5D%20REPLACE%20THESE/main.lua#L697 we should be good to merge :)

**Comment by LifeCore-Development** [comment]
Sorry about that, i left that print in accidentally when i was comparing the Lua Tables. Removed now, should be all good. I have yet to run into any other issues with it on my end with the same file.

**Comment by RazerGhost** [comment]
No problem. everything seemed to be working on my end with what i had tested which is new qb inventory + hi dev. Tested bullet fragments and casing which worked perfectly.

**Comment by LifeCore-Development** [comment]
Yep same setup I use. If i run across any issues in my city using it, I will put another pull request for fixes to it.

**Comment by RazerGhost** [comment]
Oh btw could you add the inventory snippet you had in the other pr to this one?

**Comment by HapticDevSys** [comment]
I don't know how to do that 🤣 I'm new to github

**Pull request merged**
