### PR TITLE
Evidence to fix lab with new-qb-inventory

### PR DESCRIPTION
**Pull request by LifeCore-Development**

### CODE REVIEW

**Comment by LeSiiN** [comment]
@RazerGhost pls also test this one :P

**Comment by LeSiiN** [comment]
@LifeCore-Development  thank you so much!

**Comment by LifeCore-Development** [comment]
No problem, I use this on my own server and im the middle of a remake so figured id share the fixes I had to do. Sorry if its not amazing code.

**Comment by RazerGhost** [comment]
Started my test yesterday but didnt finish everything yet :)

**Comment by RazerGhost** [comment]
Added this and mentioned you in the commit :)

**Pull request closed without merging**
